#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|project|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "❌ Aborting commit: Your commit message is invalid. Please use the following format:" >&2
    echo "" >&2
    echo "    <type>[optional scope]: <description>" >&2
    echo "" >&2
    echo "For example:" >&2
    echo "    feat(core): add new feature" >&2
    echo "    fix(view): fix view bugs" >&2
    echo "    chore: update dependencies" >&2
    echo "    project: update project structure" >&2
    echo "    docs: add documentation" >&2
    echo "    test: add tests" >&2
    echo "    style: fix code style" >&2
    echo "    refactor: refactor code" >&2
    echo "    perf: improve performance" >&2
    echo "    build: build system" >&2
    echo "    ci: ci related" >&2
    echo "    revert: revert previous commit" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "❌ Aborting commit: Your commit message is too long." >&2
    exit 1
fi